name: finalproject
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
#  google_fonts: ^6.2.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: 2.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0
  google_sign_in: ^5.1.0
  sign_in_with_apple: ^4.0.0
  flutter_facebook_auth: ^5.0.6
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  json_serializable: ^6.8.0
  multi_select_flutter: ^4.1.3
  pretty_dio_logger: ^1.3.1
  awesome_dio_interceptor: ^1.2.0
  permission_handler: ^11.3.1
  json_annotation: ^4.9.0
  connectivity_plus: ^4.0.1
  mockito: ^5.4.4

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4  # Ensure this is in both dependencies and dev_dependencies
  build_runner: ^2.4.11  # Add this here to ensure the mocks are generated during testing

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
